//! Real-time float safety, denormal mitigation, and non-finite containment.
//!
//! Provides defense-in-depth against floating-point anomalies that can compromise
//! audio thread performance or corrupt signal graphs:
//!
//! - [`FloatSafetyMode`]: Central policy governing subnormal/denormal numbers.
//! - [`NonFinitePolicy`]: Containment strategy for `NaN` and `±Inf` generated by defective DSP nodes.
//! - [`NonFiniteIncident`]: Structured diagnostic identifying the offending node, channel, and value.

use serde::{Deserialize, Serialize};
use std::borrow::Cow;

use crate::buffer::flush_denormal;
use crate::dsp_utils::enable_flush_zero_denormals_on_current_thread;

/// Policy controlling handling of subnormal/denormal floating-point values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FloatSafetyMode {
    /// Hardware and software flush-to-zero (FTZ / DAZ enabled).
    /// Prevents CPU stalls on filter decays, reverb tails, and silence.
    #[default]
    FlushToZero,
    /// Software-only branchless denormal suppression.
    DenormalSuppress,
    /// Strict IEEE 754 compliance without flush-to-zero.
    StrictIEEE,
}

impl FloatSafetyMode {
    /// Configure the current thread according to this policy.
    pub fn apply_to_current_thread(&self) -> bool {
        match self {
            Self::FlushToZero => enable_flush_zero_denormals_on_current_thread(),
            Self::DenormalSuppress | Self::StrictIEEE => true,
        }
    }

    /// Clean a single sample according to the active mode.
    #[inline(always)]
    pub fn sanitize_sample(&self, s: f32) -> f32 {
        match self {
            Self::FlushToZero | Self::DenormalSuppress => flush_denormal(s),
            Self::StrictIEEE => s,
        }
    }
}

/// Policy for handling non-finite values (`NaN`, `+Inf`, `-Inf`) in the audio path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NonFinitePolicy {
    /// Do not inspect or modify samples (fastest, unsafe).
    Ignore,
    /// Detect and count non-finite samples without modifying the signal.
    Detect,
    /// Clamp non-finite values: `NaN` -> 0.0, `+Inf` -> 1.0, `-Inf` -> -1.0.
    #[default]
    Clamp,
    /// Replace any non-finite sample with pure silence (0.0).
    Silence,
    /// Silence the corrupted channel/block to prevent downstream poisoning.
    BypassNode,
}

/// Structured diagnostic describing a non-finite arithmetic incident.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NonFiniteIncident {
    /// ID of the node that produced the non-finite value, if known.
    pub node_id: Option<u32>,
    /// Name or descriptor of the stage.
    pub node_name: Option<Cow<'static, str>>,
    /// Frame index within the processed audio block.
    pub sample_index: usize,
    /// Audio channel where the non-finite occurred.
    pub channel: usize,
    /// The exact floating-point value encountered (`NaN`, `+Inf`, or `-Inf`).
    pub value: f32,
    /// Active graph generation ID.
    pub graph_generation: u64,
}

/// Scans and remediates an audio block in-place according to [`NonFinitePolicy`].
///
/// **Realtime guarantee**: This function performs zero heap allocations.
/// If an `on_incident` callback is provided, it receives an incident record.
pub fn contain_non_finite_block<F>(
    samples: &mut [f32],
    channels: usize,
    policy: NonFinitePolicy,
    node_id: Option<u32>,
    node_name: Option<&'static str>,
    generation: u64,
    mut on_incident: F,
) -> usize
where
    F: FnMut(NonFiniteIncident),
{
    if policy == NonFinitePolicy::Ignore || samples.is_empty() || channels == 0 {
        return 0;
    }

    let mut non_finite_count = 0usize;
    let frames = samples.len() / channels;

    for frame_idx in 0..frames {
        let frame_offset = frame_idx * channels;
        for c in 0..channels {
            let s = samples[frame_offset + c];
            if !s.is_finite() {
                non_finite_count += 1;

                on_incident(NonFiniteIncident {
                    node_id,
                    node_name: node_name.map(Cow::Borrowed),
                    sample_index: frame_idx,
                    channel: c,
                    value: s,
                    graph_generation: generation,
                });

                match policy {
                    NonFinitePolicy::Ignore => {}
                    NonFinitePolicy::Detect => {}
                    NonFinitePolicy::Clamp => {
                        samples[frame_offset + c] = if s.is_nan() {
                            0.0
                        } else if s.is_sign_positive() {
                            1.0
                        } else {
                            -1.0
                        };
                    }
                    NonFinitePolicy::Silence | NonFinitePolicy::BypassNode => {
                        samples[frame_offset + c] = 0.0;
                    }
                }
            }
        }
    }

    if policy == NonFinitePolicy::BypassNode && non_finite_count > 0 {
        // If node bypass requested on failure, silence entire output block
        samples.fill(0.0);
    }

    non_finite_count
}

/// Scans and remediates planar audio blocks in-place according to [`NonFinitePolicy`].
///
/// **Realtime guarantee**: Zero dynamic allocations.
pub fn contain_non_finite_planes<F>(
    planes: &mut [&mut [f32]],
    policy: NonFinitePolicy,
    node_id: Option<u32>,
    node_name: Option<&'static str>,
    generation: u64,
    mut on_incident: F,
) -> usize
where
    F: FnMut(NonFiniteIncident),
{
    if policy == NonFinitePolicy::Ignore || planes.is_empty() {
        return 0;
    }

    let mut non_finite_count = 0usize;

    for (c, plane) in planes.iter_mut().enumerate() {
        for (i, s) in plane.iter_mut().enumerate() {
            if !s.is_finite() {
                non_finite_count += 1;

                on_incident(NonFiniteIncident {
                    node_id,
                    node_name: node_name.map(Cow::Borrowed),
                    sample_index: i,
                    channel: c,
                    value: *s,
                    graph_generation: generation,
                });

                match policy {
                    NonFinitePolicy::Ignore | NonFinitePolicy::Detect => {}
                    NonFinitePolicy::Clamp => {
                        *s = if s.is_nan() {
                            0.0
                        } else if s.is_sign_positive() {
                            1.0
                        } else {
                            -1.0
                        };
                    }
                    NonFinitePolicy::Silence | NonFinitePolicy::BypassNode => {
                        *s = 0.0;
                    }
                }
            }
        }
    }

    if policy == NonFinitePolicy::BypassNode && non_finite_count > 0 {
        for plane in planes.iter_mut() {
            plane.fill(0.0);
        }
    }

    non_finite_count
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_contain_non_finite_clamp() {
        let mut block = vec![
            0.5f32,
            f32::NAN,
            2.0,
            f32::INFINITY,
            -1.0,
            f32::NEG_INFINITY,
        ];
        let mut incidents = Vec::new();

        let count = contain_non_finite_block(
            &mut block,
            2,
            NonFinitePolicy::Clamp,
            Some(42),
            Some("test_node"),
            1,
            |inc| incidents.push(inc),
        );

        assert_eq!(count, 3);
        assert_eq!(incidents.len(), 3);
        assert_eq!(incidents[0].node_id, Some(42));
        assert!(incidents[0].value.is_nan());

        // NaN -> 0.0, +Inf -> 1.0, -Inf -> -1.0
        assert_eq!(block[0], 0.5);
        assert_eq!(block[1], 0.0);
        assert_eq!(block[2], 2.0);
        assert_eq!(block[3], 1.0);
        assert_eq!(block[4], -1.0);
        assert_eq!(block[5], -1.0);
    }

    #[test]
    fn test_contain_non_finite_silence() {
        let mut block = vec![0.5f32, f32::NAN, f32::INFINITY, 0.2];
        let count = contain_non_finite_block(
            &mut block,
            2,
            NonFinitePolicy::Silence,
            None,
            None,
            0,
            |_| {},
        );

        assert_eq!(count, 2);
        assert_eq!(block[1], 0.0);
        assert_eq!(block[2], 0.0);
        assert_eq!(block[0], 0.5);
        assert_eq!(block[3], 0.2);
    }
}
